### ISSUE TITLE
[BUG] - Некорректная работа свайпа в Cells

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#101]
**App version**: 1649500467
**OS version**: 15.1
**Описание**: 
в ActionBar - type default и Type Secondary, если изначально свайпаем влево, затем делаем Disable, и жмем опять на то,что свайпнули - свайп уходит

**Шаги воспроизведения:**
1. Заходим в Cells
2. Заходим в Type Default и Type Secondary 
3. Свайпаем влево
4. Жмем Disable
5. Нажимаем на свайп

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

https://user-images.githubusercontent.com/101252323/169830247-d5263b70-85dc-4d2f-8b38-b54dd57b0bf1.mov

**Comment by KirBorisov96** [comment]
1d
