### ISSUE TITLE
[FEATURE] - Text Blocks корректировка дизайна

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#102]
**Описание задачи:**
Header не совпадает с дизайном, нужно уточнить, либо менять как в фигме, либо в фигме неактуальная инфа.
Accordion - нет кнопки Disable. Paragraph - не работает(работает со SwiftUI). Link - нет кнопки Disable. Padding - не работает(работает со SwiftUI)

**Фреймворк**
Text Blocks

**Ресурсы:**
Ссылка на макеты или ресурсы...

1 - скрины header с фигмы и с эмулятора
<img width="175" alt="Снимок экрана 2022-06-06 в 12 12 43" src="https://user-images.githubusercontent.com/101252323/172132170-276c610a-de00-409f-a3f7-c149e3cc37da.png">
![Simulator Screen Shot - iPhone 8 - 2022-06-06 at 12 12 47](https://user-images.githubusercontent.com/101252323/172132179-0b09893b-951e-47f8-9dcb-3f578a0b1294.png)

2 - Accordion скрины несовпадения, нет disabled
<img width="245" alt="Снимок экрана 2022-06-06 в 12 13 59" src="https://user-images.githubusercontent.com/101252323/172132367-5da956be-c211-4c20-adf5-63f11a4e64b1.png">
![Simulator Screen Shot - iPhone 8 - 2022-06-06 at 12 13 42](https://user-images.githubusercontent.com/101252323/172132379-f970e7df-4565-455a-961c-608b549ccc69.png)

3- paragrapf - на ui kit  не реализован, возможно нужно завести отдельную задачу

4 - Link - нет disabled/default 

<img width="245" alt="Снимок экрана 2022-06-06 в 12 16 13" src="https://user-images.githubusercontent.com/101252323/172132721-a5e9e4fd-a2c0-4ed2-87b2-34499d5db8c2.png">
![Simulator Screen Shot - iPhone 8 - 2022-06-06 at 12 15 59](https://user-images.githubusercontent.com/101252323/172132729-ea333ee7-7cd5-4c56-b34b-d201f858425a.png)

5- padding - не реализован на ui kit - возможно так же нужна отдельная задача

**Comment by KirBorisov96** [comment]
1d
