### ISSUE TITLE
[FEATURE] - Tabs не хватает разделов

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#103]
**Описание задачи:**
Standard Tabs - нет разделов Four Controls, Five Controls. Logo Tabs - тоже самое. Outline Slider tabs - нет раздела Notifications. Underline Slider Tabs - нет раздела Notifications

**Фреймворк**
SwiftUI/UIkit

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by KirBorisov96** [comment]
1d
