### ISSUE TITLE
[FEATURE] - Tags&Chips - Emoji уточнение

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#107]
**Описание задачи:**
Tags&Chips - Emoji по фигме без смайлика. Нужен там смайлик или нет нужно уточнить

**Фреймворк**
Tags&Chips

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by KirBorisov96** [comment]
2h

**Comment by KirBorisov96** [comment]
задача реализована
