### ISSUE TITLE
[FEATURE] - Alerts&onboarding доработка

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#108]
**Описание задачи:**
Alerts&onboarding - Alert. По фигме Header, по факту - Заголовок в одну или две строки. Онбординга нет. Zeroscreen так же не по фигме. Кнопка Хорошо в zeroscreen не работает. Кнопка хорошо на Error View запускает вечный спиннер

UI + SwiftUI
**Фреймворк**
Alerts&onboarding

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by KirBorisov96** [comment]
2h
