### ISSUE TITLE
[FEATURE] - SwiftUI отсутствует Liner

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#116]
**Описание задачи:**
Page Controls co Swiftui - нет Liner

**Фреймворк**
Liner

**Ресурсы:**
Ссылка на макеты или ресурсы...
<img width="360" alt="Снимок экрана 2022-05-23 в 16 22 35" src="https://user-images.githubusercontent.com/101252323/169829020-144ce8ff-65a9-4b74-9c71-de80ad9d32f7.png">
![Simulator Screen Shot - iPhone 8 - 2022-05-23 at 16 21 39](https://user-images.githubusercontent.com/101252323/169829032-013bb81b-21f7-4a34-8e8d-f30fe46db521.png)

**Comment by KirBorisov96** [comment]
2d
