### ISSUE TITLE
[BUG] - SwiftUI добавить элемент Time Picker

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#117]
**App version**: 1649500467
**OS version**: 15.1
**Описание**: 
SwiftUI не работает Time Picker

**Шаги воспроизведения:**
1. Включаем SwiftUi
2. Выбираем Time Picker
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

**Comment by KirBorisov96** [comment]
2d

**Comment by KirBorisov96** [comment]
Реализовывать не нужно
