### ISSUE TITLE
[BUG] - Устранить утечку памяти в chatInput

### ISSUE THREAD

**Issue by KirBorisov96** [admiral-team/admiralui-ios#13]
+ Chat SwiftUI нестабильное поведение Chat Input

**Comment by Andyatkov** [comment]
1d

**Comment by KirBorisov96** [comment]
Утечка памяти возникает в Text(STRING), где STRING более 9 символов:

Скриншот где STRING < 9 символов:
<img width="1324" alt="Снимок экрана 2022-04-14 в 16 59 33" src="https://user-images.githubusercontent.com/100690555/163407804-d3800383-dfce-46c7-8085-8db8c7ac802b.png">

Скриншот где STRING > 9 символов:
<img width="1324" alt="Снимок экрана 2022-04-14 в 17 00 23" src="https://user-images.githubusercontent.com/100690555/163407866-c4ce014f-545c-4445-8dc9-d3628ed50c66.png">
