### ISSUE TITLE
[BUG] - SwiftUi некорректная работа слайдера

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#141]
**App version**: 1650361859
**OS version**: 15.1
**Описание**: 
SwiftUi когда в слайде от 100 до 1000 пытаюсь тянуть левую точку, доходит примерно до 162, затем сбрасывается и просто экран уходит вправо
плюс, если обе точки оставлю в 100, то обратно уже не вернуть

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

**Comment by Andyatkov** [comment]
1d

**Comment by Almazovivan** [comment]
Закрато в рамках реквеста
https://github.com/admiral-team/admiralui-ios/pull/173/files
