### ISSUE TITLE
[BUG] - UnderlineSegmentedControl not changed segment

### ISSUE THREAD

**Issue by sashaputsik** [admiral-team/admiralui-ios#157]
- [ ] @##**App version**: 4.2.0

**OS version**: 15
**Описание**: 
Не возможно изменить сегмент на другой при нажатии

**Шаги воспроизведения:**
1. Выбрать сегмент

**Фактический результат:**
> Сегмент не меняется

**Ожидаемый результат:**
>Сегмент меняется

**Comment by sashaputsik** [comment]
https://user-images.githubusercontent.com/47576503/165081314-8920f008-3d42-4181-a1c5-8fe563e1e4ec.mov

**Comment by Almazovivan** [comment]
Сделано в рамках хотфикса 5.0.2
