### ISSUE TITLE
[BUG] - Некорректная работа 2 строчки в slider

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#160]
**App version**: 5.0.0(6)
**OS version**: 15.2
**Описание**: 
в slider на второй строчке изначально optional label не видно полностью, additional так же верстка поехала. Когда выбираю эту строку то все ок

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

**Comment by Andyatkov** [comment]
Баг
<img width="577" alt="Снимок экрана 2022-04-25 в 16 14 17" src="https://user-images.githubusercontent.com/8963238/165096447-c26cfd59-d9ac-466b-a823-2b805f9b0863.png">

**Comment by Andyatkov** [comment]
1d

**Comment by Almazovivan** [comment]
Закрато в рамках реквеста
https://github.com/admiral-team/admiralui-ios/pull/173/files
