### ISSUE TITLE
[BUG] - Некорректное удаление дефолтной темы

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#161]
**App version**: 5.0.0(6)
**OS version**: 15.2
**Описание**: 
Когда удаляю тему  и выхожу из приложения свайпом вверх, то темы появляются снова, но только дефолтные

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

**Comment by Andyatkov** [comment]
Темы дефолтные не должны удаляться из телефона(light dark sme light/dark)
