### ISSUE TITLE
[FEATURE] - Сопоставить дизайн в small informers с фигмой

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#165]
**Описание задачи:**
Сопоставить дизайн в small informers с фигмой

**Фреймворк**
SwiftUI

**Ресурсы:**
Ссылка на макеты или ресурсы...

<img width="358" alt="Снимок экрана 2022-04-25 в 16 53 32" src="https://user-images.githubusercontent.com/101252323/165103423-126fd5f6-4110-4897-9891-1308dacffa34.png">
![Simulator Screen Shot - iPhone 8 - 2022-04-25 at 16 53 47](https://user-images.githubusercontent.com/101252323/165103473-5e3ab1e5-dfaa-4879-adfd-0f4502aa48f8.png)

**Comment by KirBorisov96** [comment]
2h

**Comment by KirBorisov96** [comment]
Была проведена доработка компонента
