### ISSUE TITLE
[FEATURE] - Необходимо убрать возможность удаления дефолтной темы в Themes

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#168]
**Описание задачи:**
Необходимо убрать возможность удаления дефолтной темы в Themes (SME Light, SME Dark)
Убрать иконки удаления 

**Фреймворк**
(UIKit/SwiftUI)

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by KirBorisov96** [comment]
4h
