### ISSUE TITLE
[FEATURE] - шапка в text fields нужно скорректировать как в фигме

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#169]
**Описание задачи:**
шапка в text fields нужно скорректировать порядок как в фигме

**Фреймворк**
UIKit/SwiftUI)

![image](https://user-images.githubusercontent.com/101252323/165295918-5359af0a-16b3-460b-8f91-787ecec4c5e5.png)

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by KirBorisov96** [comment]
2h
