### ISSUE TITLE
[FEATURE] - Правка текста

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#17]
**Описание задачи:**
Необходимо подправить текст. Сейчас Trailing elements, Нужно - Trailing Elements

**Фреймворк**
UIKit

**Ресурсы:**
(https://www.figma.com/file/zJVtz4nu2TFZwvqaCMPd1E/Admiral-Mobile-%E2%80%A8Application?node-id=8%3A32)

**Comment by KirBorisov96** [comment]
задача реализована в другом PR
