### ISSUE TITLE
[FEATURE] - Убрать точки в конце строки ввода в TextField

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#187]
**Описание задачи:**
Убрать точки в конце строки ввода в TextField Masked.
![Uploading Снимок экрана 2022-05-05 в 16.10.56.png…]()

**Фреймворк**
UIKit

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by Almazovivan** [comment]
TextField Masked работает корректно
