### ISSUE TITLE
[BUG] - Некорректное отображение кнопки "выбрано" на теме

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#201]
**App version**: 6.0.0
**OS version**: 15.2
**Описание**: 
Некорректное отображение кнопки "выбрано" на наименование темы
Некорректное отображение строки наименования названия темы(swiftui + ui kit)если наименование слишком длинное, то «выбрано» вообще не видно

**Шаги воспроизведения:**
1. Главная
2. Themes
3. Входим в тему, которую можно редактировать4. 
4. Переименовываем с кучей символов5. 
5. Жмем сохранить
6. Жмем применить
7. Жмем назад
8. Возле наименования темы будет неполностью написано "выбрано"  

**Фактический результат:**
> Некорректный результат, слово "выбрано" написано неполностью

**Ожидаемый результат:**
> Корректный результат, слово "выбрано" написано полностью целиком

Скрины прилагаю, видео не могу, тк не позволяет размер

![Simulator Screen Shot - iPhone 8 - 2022-05-11 at 18 08 23](https://user-images.githubusercontent.com/101252323/167885294-a2665ce8-515e-4b91-8700-aa376ee63120.png)
![Simulator Screen Shot - iPhone 8 - 2022-05-11 at 18 08 26](https://user-images.githubusercontent.com/101252323/167885309-1ee8d843-2e06-4ba2-8548-34083bfba956.png)
![Simulator Screen Shot - iPhone 8 - 2022-05-11 at 18 08 30](https://user-images.githubusercontent.com/101252323/167885316-68cda34a-efeb-40fb-817f-0c1db62ce1fc.png)
![Simulator Screen Shot - iPhone 8 - 2022-05-11 at 18 08 35](https://user-images.githubusercontent.com/101252323/167885318-389f5f28-aeba-4cf1-8738-688889fbec43.png)
![Simulator Screen Shot - iPhone 8 - 2022-05-11 at 18 08 40](https://user-images.githubusercontent.com/101252323/167885321-85389ca2-8b5a-447c-b1df-b7909d3a6687.png)
![Simulator Screen Shot - iPhone 8 - 2022-05-11 at 18 08 44](https://user-images.githubusercontent.com/101252323/167885326-b5bfc5c1-86f5-466b-b6ad-21a525247f8c.png)
![Simulator Screen Shot - iPhone 8 - 2022-05-11 at 18 08 49](https://user-images.githubusercontent.com/101252323/167885329-b0321d0e-766c-4fa7-913b-55aabfac6e3c.png)
![Simulator Screen Shot - iPhone 8 - 2022-05-11 at 18 08 51](https://user-images.githubusercontent.com/101252323/167885335-251294ee-b957-4e46-91b5-2c0dbea1642d.png)

**Comment by KirBorisov96** [comment]
1d
