### ISSUE TITLE
[FEATURE] - Нужно вернуть возможность переименования темы в SME

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#218]
**Описание задачи:**
Нужно вернуть возможность переименования темы в SME, была убрана возможность удаления темы SME, вместе с этой задачей убрали карандашик, который редактировал наименование темы

**Фреймворк**
UIKit/SwiftUI

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by KirBorisov96** [comment]
4h
