### ISSUE TITLE
[FEATURE] - Добавить значек рубль в слайдер на UIKit

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#219]
**Описание задачи:**
Добавить значек рубль в слайдер на UIKit

**Фреймворк**
UIKit

**Ресурсы:**
Ссылка на макеты или ресурсы...
<img width="360" alt="Снимок экрана 2022-05-23 в 16 24 18" src="https://user-images.githubusercontent.com/101252323/169829297-91f2090e-6dc7-4f6d-ab7b-6d6801779be4.png">

**Comment by KirBorisov96** [comment]
1d
