### ISSUE TITLE
[BUG] - В standard tabs, logo tabs - появляется линия прокрутки(swiftUI)

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#220]
**App version**: 7.0.0
**OS version**: 15,2
**Описание**: 
В standard tabs, logo tabs - появляется линия прокрутки(swiftUI) справа

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Есть линия прокрутки

**Ожидаемый результат:**
> Линии быть не должно

**Comment by KirBorisov96** [comment]
1h
