### ISSUE TITLE
[BUG] - Повторное всплывающее сообщение в action

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#221]
https://user-images.githubusercontent.com/101252323/169809150-a31cd6a0-dcbe-41b0-8184-112c2b41ef57.mov

**App version**: 7.0.0
**OS version**: 15.2
**Описание**: 
жмем показать action  появляется надпись, что через 5 сек сообщение будет удалено/ 5 сек проходит сообщение пропадает и появляется новое на 1 сек(покажу при созвоне) - swiftUI

**Шаги воспроизведения:**
1. Action
2. показать action
3. Шаг 3

**Фактический результат:**
> всплывает 2 сообщения action

**Ожидаемый результат:**
> должно всплывать одно сообщение

**Comment by KirBorisov96** [comment]
1d
