### ISSUE TITLE
[BUG] - Toolbar - сообщение "количество пунктов меню" не вмещается

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#222]
**App version**: 7.0.0
**OS version**: 15.2
**Описание**: 
Toolbar - сообщение "количество пунктов меню" не вмещается

UIkit
**Шаги воспроизведения:**
1. заходим в toolbar
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> количество пунктов ме..

**Ожидаемый результат:**
> Либо количество пунктов меню полностью должно вмещаться, либо как на swiftui - количество пунктов
![Simulator Screen Shot - iPhone 8 - 2022-05-23 at 14 18 46](https://user-images.githubusercontent.com/101252323/169808059-a3630543-71d4-4c2a-b351-d2944184f931.png)

**Comment by KirBorisov96** [comment]
Надо добавить скрины и описание фреймворка !!! @Evgeniy-93

**Comment by KirBorisov96** [comment]
4h
