### ISSUE TITLE
[BUG] - Появляющееся сообщение на главной после переключения с uiKit на swiftUI

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#223]
**App version**: 7.0.0.
**OS version**: 15.2
**Описание**: 
> Появляющееся сообщение на главной после переключения с uiKit на swiftUI

**Шаги воспроизведения:**
1. Главная страница
2. Включен UiKit
3. Заходим в настройки и нажимаем на swiftUi
4. Переходим на главную

https://user-images.githubusercontent.com/101252323/169808542-ef85b20c-b517-4c0a-aeea-03498c400067.mov

 
**Фактический результат:**
> Появляется сообщение - сообщение будет удалено через 5 сек

**Ожидаемый результат:**
> Никакого сообщения быть не должно

**Comment by KirBorisov96** [comment]
1d
