### ISSUE TITLE
[BUG] -LogoTabs перемещение медленное между логотипами(swiftUI)

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#224]
**App version**: 7.0.0
**OS version**: 15.2
**Описание**: 
> Когда в лого табс переключаюсь между иконками, то само переключение происходит медленно

**Шаги воспроизведения:**
1. Logo tabs
2. Переключаюсь между иконками
3. Шаг 3

**Фактический результат:**
> Перемещение между лого происходит медленно

**Ожидаемый результат:**
> Перемещение должно происходить быстро

**Comment by KirBorisov96** [comment]
1d
