### ISSUE TITLE
[BUG] - Underline Slider Tabs - Notifications - разделы не кликабельны(swiftUI)

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#225]
**App version**: 7.0.0
**OS version**: 15.2
**Описание**: 
> Underline Slider Tabs - Notifications - разделы не кликабельны(swiftUI)

**Шаги воспроизведения:**
1. заходим в данный раздел
2. пробуем переключаться между notifications
3. Шаг 3

**Фактический результат:**
> переключение не происходит

**Ожидаемый результат:**
> должно переключаться

https://user-images.githubusercontent.com/101252323/169828493-c63aec06-5923-4fac-8ca3-d5db998b767f.mov

**Comment by KirBorisov96** [comment]
1d
