### ISSUE TITLE
[FEATURE] - Убрать вьюху из Big Informers

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#229]
**Описание задачи:**
Убрать вьюху (сообщение до 1 500 000) из Big Informers

**Фреймворк**
UIKit/SwiftUI

**Ресурсы:**
Ссылка на макеты или ресурсы...

раньше было так 
![image](https://user-images.githubusercontent.com/101252323/169786808-b74c46ce-9d4d-421d-aab6-5066083394b3.png)

теперь так

![image](https://user-images.githubusercontent.com/101252323/169786856-f3fae3f5-ad39-4f52-bc3c-660b3303d20b.png)

**Comment by KirBorisov96** [comment]
2h
