### ISSUE TITLE
[FEATURE] - SwiftUI Chat Input бабл не поднимает существующие сообщения 

### ISSUE THREAD

**Issue by KirBorisov96** [admiral-team/admiralui-ios#23]
**Описание задачи:**
Краткое описание задачи...

**Фреймворк**
Фреймворк для которого нужно выполнить доработку (UIKit/SwiftUI)...

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by Andyatkov** [comment]
1d
