### ISSUE TITLE
[BUG] - Apple Pay значок не виден в темной теме

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#238]
**App version**: 7.0.0
**OS version**: 15.2
**Описание**: 
> При переключении на темную тему не виден значок apple pay

**Шаги воспроизведения:**
1. Включаем темную тему
2. Заходим в tabs
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге
![Simulator Screen Shot - iPhone 8 - 2022-05-24 at 12 30 43](https://user-images.githubusercontent.com/101252323/170000279-66bbcfff-9b51-4e67-955b-24ec2cf43e9a.png)

**Comment by KirBorisov96** [comment]
Задача не решаема, т.к будет несоответствие дизайна
