### ISSUE TITLE
[BUG] - Underline center tabs - five controls - отсутствует four

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#254]
**App version**: 8.0.0
**OS version**: 15.2
**Описание**: 
> Underline center tabs - five controls - отсутствует four (UI kit)

**Шаги воспроизведения:**
1. Заходим в раздел Underline slider tabs
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге
![image](https://user-images.githubusercontent.com/101252323/172162782-f71d5640-862d-440d-bcd7-a167473e9a69.png)

**Comment by Almazovivan** [comment]
Закрыто в рамках задачи
https://github.com/admiral-team/admiralui-ios/pull/259
