### ISSUE TITLE
[BUG] - UIKit Bottom Sheet темные темы

### ISSUE THREAD

**Issue by KirBorisov96** [admiral-team/admiralui-ios#26]
**Описание задачи:**
Краткое описание задачи...

**Фреймворк**
Фреймворк для которого нужно выполнить доработку (UIKit/SwiftUI)...

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by Andyatkov** [comment]
1d

**Comment by Almazovivan** [comment]
Баг исправлен. Проверил и обсудил с Ларой.
