### ISSUE TITLE
[BUG] - Добавить возможность установить локаль дат в календаре.

### ISSUE THREAD

**Issue by Lesnichi** [admiral-team/admiralui-ios#263]
**App version**: Admiral 8.0.0
**OS version**: iOS 14.6
**Описание**:
В компоненте CalendarView (UIKit) не работает локализация.

**Шаги воспроизведения:**
1. Убедится что в настройках устройства стоит русский язык
2. Открыть календарь
3. Зафиксировать название месяца и дней недели

**Фактический результат:**
Названия на английском языке

**Ожидаемый результат:**
Названия на русском языке

![Bug - Admiral iOS UIKit - Calendar](https://user-images.githubusercontent.com/51000407/173584509-e16d0035-1ef2-47bf-bef3-81467ebe3b88.jpeg)

**Comment by KirBorisov96** [comment]
Отписался Владу как можно решить эту проблему
![Simulator Screen Shot - iPhone 8 - 2022-06-17 at 16 55 48](https://user-images.githubusercontent.com/100690555/174314099-4a8b7b7d-516d-4f25-bda5-efa9f46d0669.png)

<img width="422" alt="Снимок экрана 2022-06-17 в 16 56 03" src="https://user-images.githubusercontent.com/100690555/174314107-c310ec49-126d-48e7-8315-891cbca8ffb7.png">
