### ISSUE TITLE
[BUG] - Error view – при нажатии на «хорошо» идет бесконечная загрузка

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#291]
**App version**: 9.1.0
**OS version**: 15.2
**Описание**: 
> Error view – при нажатии на «хорошо» идет бесконечная загрузка UIkit + SwiftUI

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

**Comment by Almazovivan** [comment]
Экран работает корректно
