### ISSUE TITLE
[BUG] - Некорректное переключение тем

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#293]
**App version**: 9.1.0
**OS version**: 15.2
**Описание**: 
> Некорректное переключение тем на SwiftUI and UIkit. Проблема давняя, видео прикладываю

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

https://user-images.githubusercontent.com/101252323/177140139-4d46a116-31c5-44a4-8890-34a382d572f4.MOV

**Comment by KirBorisov96** [comment]
Я не вижу здесь проблемы, нужно боле подробное описание

**Comment by KirBorisov96** [comment]
Невозможно исправить проблему т.к мы дёргаем системные методы
