### ISSUE TITLE
[FEATURE] - Нужно сопоставить Alerts SwiftUI и UIkit

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#312]
**Описание задачи:**
Нужно сопоставить Alerts SwiftUI и UIkit (разница на фото – 1 фото Uikit, 2 фото SwiftUI)

**Фреймворк**
UIKit/SwiftUI

**Ресурсы:**
Ссылка на макеты или ресурсы...

![image](https://user-images.githubusercontent.com/101252323/179487705-7fbb0e16-1381-4565-8b71-3bd171b72337.png)
![image](https://user-images.githubusercontent.com/101252323/179487748-923d0925-babe-4900-a95d-7427d58b18db.png)

**Comment by KirBorisov96** [comment]
1d
