### ISSUE TITLE
[BUG] - Бегающая строка в слайдере 

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#335]
**App version**: 10.1.0
**OS version**: 15.2
**Описание**: 
> Подробное описание проблемы
Бегает слово «До» про переключении слайдера и значок рубль. Данная проблема на UIKit и SwiftUI. Так же по просьбе Антона кидаю ссылку 

https://developer.apple.com/documentation/swiftui/font/monospaceddigit()

выставить mono шрифт 
проверить на разных осях

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

https://user-images.githubusercontent.com/101252323/182651655-6f51d9cf-4ff8-4f60-8460-b47cb207a37e.MOV

https://user-images.githubusercontent.com/101252323/182651659-f8a929da-7241-441b-825b-5ea448aa1b9b.MOV

**Comment by KirBorisov96** [comment]
1d

**Comment by KirBorisov96** [comment]
нужно использовать шрифт monospace для того чтобы решить бегание строки
