### ISSUE TITLE
[BUG] - Не отрабатывает тест в Actionbar

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#337]
**App version**: 10.1.0
**OS version**: 15.2
**Описание**: 
> Подробное описание проблемы
При автотестах заходим в Actionbar - прописываю:

app.staticTexts["Disabled"].tap()
app.staticTexts["Default"].tap()

Disabled работает
Default нет

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге
![Simulator Screen Shot - iPhone 8 - 2022-08-04 at 19 52 57](https://user-images.githubusercontent.com/101252323/182907085-4f951cf0-552e-4f4f-99ed-ca32c29b6b54.png)

**Comment by KirBorisov96** [comment]
1d
