### ISSUE TITLE
[BUG] - Неккоректное отображение Apple Wallet

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#340]
**App version**: 10.1.0
**OS version**: 15.2
**Описание**: 
> Подробное описание проблемы
Buttons - other buttons, если переключаю на темную тему или SME Dark, то кнопка неккоректно отображается
**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге
![5ECB4CA2-7407-431B-A4C6-A06A0D1CF2E6](https://user-images.githubusercontent.com/101252323/183626862-05aa93ab-9b58-4c0b-8795-2b5edc9da981.png)
![1B857887-09AC-4EBE-96C6-FEC4B531BFE1](https://user-images.githubusercontent.com/101252323/183626875-f74ca827-d304-4ff4-a57b-fb7cf2d50698.png)

**Comment by KirBorisov96** [comment]
2h
