### ISSUE TITLE
[BUG] - UIKit TimePicker странное поведение при попытке ввода и удаления некорректного значения

### ISSUE THREAD

**Issue by KirBorisov96** [admiral-team/admiralui-ios#42]
**App version**: Версия приложения
**OS version**: Версия операционной системы
**Описание**: 
> Подробное описание проблемы

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

**Comment by Andyatkov** [comment]
2d
