### ISSUE TITLE
[FEATURE] - Разобрать изображения PrivateImages

### ISSUE THREAD

**Issue by Almazovivan** [admiral-team/admiralui-ios#444]
**Описание задачи:**
Заменить изображения на изображения из нашей библиотеки
Переименовать раздел в SystemImages
Заменить изображения на прозрачные

**Фреймворк**
Фреймворк для которого нужно выполнить доработку (UIKit/SwiftUI)...

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by KirBorisov96** [comment]
1d
