### ISSUE TITLE
[FEATURE] - Сопоставить дизайн Bagdes с Фигмой

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#469]
**Описание задачи:**
Краткое описание задачи...
В фигме указаны значки бриллианта, по факту "подарок"

**Фреймворк**
Фреймворк для которого нужно выполнить доработку (UIKit/SwiftUI)...

**Ресурсы:**
Ссылка на макеты или ресурсы...

![image](https://user-images.githubusercontent.com/101252323/187678404-8b1a3ee3-5642-457a-a1dc-93eba8a55ae6.png)
![image](https://user-images.githubusercontent.com/101252323/187678431-69573536-545a-481c-9aeb-d023d4926920.png)
![image](https://user-images.githubusercontent.com/101252323/187678488-f6432e86-f8fb-4b83-a07f-4fb1093fc872.png)
![image](https://user-images.githubusercontent.com/101252323/187678505-849a8e06-83cd-4fc6-bc44-1bc8a701d91f.png)

**Comment by KirBorisov96** [comment]
1d
