### ISSUE TITLE
[FEATURE] - Привести к одному размеру Zeroscreen

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#471]
**Описание задачи:**
На скриншотах видно, что UIKit и SwiftUI отличается по высоте, нужно привести к одному виду

на 1 фото UIKit

**Фреймворк**
Фреймворк для которого нужно выполнить доработку (UIKit/SwiftUI)...

**Ресурсы:**
Ссылка на макеты или ресурсы...
![image](https://user-images.githubusercontent.com/101252323/187679656-bd6bada0-1a79-4389-9ab7-41e8d5afc99f.png)
![image](https://user-images.githubusercontent.com/101252323/187679668-eaa03da1-7b90-4342-bf03-3851dd6c3c4e.png)

**Comment by KirBorisov96** [comment]
1d
