### ISSUE TITLE
[BUG] - Сопоставить пинкод с фигмой

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#481]
**App version**: 0.0.0(15)
**OS version**: 15.2
**Описание**: 
> Подробное описание проблемы
SwiftUI/UIKit - сопоставить дизайн с фигмой

1 фото - фигма
2 фото - SwiftUI
3 фото - UIKit

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге
<img width="248" alt="Снимок экрана 2022-09-01 в 14 48 15" src="https://user-images.githubusercontent.com/101252323/187906939-85185d2b-0b79-459e-9ba0-db259b7e150c.png">
![1](https://user-images.githubusercontent.com/101252323/187907323-2a2e4f47-bb16-408b-9723-a12c79343a76.jpg)
![2](https://user-images.githubusercontent.com/101252323/187907328-1d60fc5d-61c5-4f9b-a36c-063472e6db0b.jpg)

**Comment by KirBorisov96** [comment]
1d
