### ISSUE TITLE
[FEATURE] - Поиск на главной с использованием пробела

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#482]
**Описание задачи:**
Необходимо по аналогии с андроид - сделать Поиск на главной с использованием пробела. В начале ставим пробел и начинаем вводить наименование вкладки - должен корректно отработать поиск

**Фреймворк**
UIKit/SwiftUI)

**Ресурсы:**
Ссылка на макеты или ресурсы...

**Comment by KirBorisov96** [comment]
1d
