### ISSUE TITLE
[Feature] - Добавить вкладку Status history

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#52]
**Описание задачи:**
Добавить вкладку Status history

**Фреймворк**
UIKit

**Ресурсы:**
https://www.figma.com/file/zJVtz4nu2TFZwvqaCMPd1E/Admiral-Mobile-%E2%80%A8Application?node-id=8%3A32

**Comment by Almazovivan** [comment]
Закрыто, общим решением. Элемент не используется и удален из фигмы.
