### ISSUE TITLE
[BUG] - Slider - рубль не видно в темной теме

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#524]
**App version**: 11.0.0(16)
**OS version**: 15.2
**Описание**: 
> Подробное описание проблемы

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

![image](https://user-images.githubusercontent.com/101252323/190404988-2c3c2c4c-3da2-43cc-98fa-132d1a963cc6.png)

**Comment by KirBorisov96** [comment]
3h
