### ISSUE TITLE
[BUG] - Убрать блик при возвращении на экран назад в iOS 16

### ISSUE THREAD

**Issue by KirBorisov96** [admiral-team/admiralui-ios#654]
**App version**: 11.1.1
**OS version**: iOS 16
**Описание**: 

https://user-images.githubusercontent.com/100690555/203776116-57a00729-45af-45b4-ab56-949f50d613db.MP4

> Подробное описание проблемы

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

**Comment by Almazovivan** [comment]
Дубликат
