### ISSUE TITLE
[FEATURE] - Необходимо убрать скролл-бары

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#70]
**Описание задачи:**
Необходимо убрать скролл-бары, сам интерфейс должен скроллиться

**Фреймворк**
UI

**Ресурсы:**
https://www.figma.com/file/SDunEMSNR5pm4ijiDGvWR9/Admiral-Mobile-%E2%80%A8Application-new?node-id=8%3A32

![image](https://user-images.githubusercontent.com/101252323/161946429-6c309423-6800-4fa8-8438-f6764831a8af.png)
как пример

**Comment by Andyatkov** [comment]
4h
