### ISSUE TITLE
[FEATURE] - В TextField добавить возможность дать пользователям вставлять вьюшки

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#718]
**Описание задачи:**
B TextField дать возможность пользователям вставлять сюда любую вьюшку

**Фреймворк**
Фреймворк для которого нужно выполнить доработку (UIKit/SwiftUI)...

**Ресурсы:**
Ссылка на макеты или ресурсы...
![image](https://user-images.githubusercontent.com/101252323/216266954-bab02b01-e057-4869-8fc8-552058ca3532.png)

**Comment by Almazovivan** [comment]
2d
