### ISSUE TITLE
[FEATURE] - При переключении на Swift-UI появляется наименование кнопок возле "назад"

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#72]
**Описание задачи:**
Когда мы переключаем на Swift-UI, то возле стрелки назад появляется наименование, по дизайну так не должно быть

**Фреймворк**
UI

**Ресурсы:**
https://www.figma.com/file/SDunEMSNR5pm4ijiDGvWR9/Admiral-Mobile-%E2%80%A8Application-new?node-id=8%3A32

Для примера

![image](https://user-images.githubusercontent.com/101252323/161947328-535f906c-ebc4-4ccb-8f8d-6f4da6f1f37d.png)
![image](https://user-images.githubusercontent.com/101252323/161947353-db5fc116-cf81-4bca-a32f-1b7cc7e60218.png)

**Comment by Andyatkov** [comment]
Задача не решаемая(для SwiftUI будет так)

**Comment by Almazovivan** [comment]
Задача не решаемая(для SwiftUI будет так)
