### ISSUE TITLE
[BUG] - Некорректная работа в Circular(SwiftUI)

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#739]
**App version**: 0.0.0(18)
**OS version**: 16.1.1
**Описание**: 
> Подробное описание проблемы
Захожу в Circular,так как там нет кнопки six то происходит ошибка в прокрутке, выбираем Five - нажимаем на стрелку 5 раз и будет полный круг, нажимаем 6 раз и переходим на Seven. Далее выбираем условно Ten - будет всего 8 раз и на 9ый переходит на следующую кнопку. Так быть не должно

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

https://user-images.githubusercontent.com/101252323/224637664-27f0a181-d048-4715-b211-c23533fc3486.MOV

**Comment by Almazovivan** [comment]
1d
