### ISSUE TITLE
[BUG] - Краш на вертикальном календаре

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#740]
**App version**: 0.0.0(18)
**OS version**: 16.1.1
**Описание**: 
> Подробное описание проблемы
Переключаю на SwiftUI - свайпаю вертикальный календарь  и происходит 3 сценария
1) - Календарь дергается и не дает дальше свайпнуть
2) - Календарь пролагивает и попадает на 2012 год
3) - Краш приложения

**Шаги воспроизведения:**
1. Шаг 1
2. Шаг 2
3. Шаг 3

**Фактический результат:**
> Некорректный результат, которые происходит при выполнении шагов

**Ожидаемый результат:**
> Корректный результат, который должен произойти в итоге

https://user-images.githubusercontent.com/101252323/224947519-c23b2cd3-e944-4199-b3e0-7c4bb9677529.MOV

**Comment by Almazovivan** [comment]
5d
