### ISSUE TITLE
[FEATURE] - Добавление скрипта для создания XCFrameworks

### ISSUE THREAD

**Issue by Andyatkov** [admiral-team/admiralui-ios#741]

**Comment by Almazovivan** [comment]
Platform: iOS
Build ID: 1850
Version: 1681306182
Internal Version: 22
Short Version: 0.0.0
Branch Name: ’’
Install URL: https://install.appcenter.ms/orgs/Admiral-Digital-Frameworks-App/apps/AdmiralUI-iOS-Dev/releases/1850
