### ISSUE TITLE
[FEATURE] - Упорядочить вкладки в Cells

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#89]
**Описание задачи:**
Упорядочить вкладки в Cells в соответствии с фигмой

**Фреймворк**
UIKit

**Ресурсы:**
https://www.figma.com/file/SDunEMSNR5pm4ijiDGvWR9/Admiral-Mobile-%E2%80%A8Application-new?node-id=8%3A32

![image](https://user-images.githubusercontent.com/101252323/162415191-a37b8637-7ecf-4308-ba77-77bfb63bd34a.png)

**Comment by Andyatkov** [comment]
1d
