### ISSUE TITLE
[FEATURE] - типы кнопок не поделены на группы как в фигме

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#97]
**Описание задачи:**
Buttons типы кнопок не поделены на группы как в фигме

**Фреймворк**
Buttons

**Ресурсы:**

![image](https://user-images.githubusercontent.com/101252323/162745721-5b9b1ca0-dce8-4138-9294-9ec711687169.png)

**Comment by KirBorisov96** [comment]
1d
