### ISSUE TITLE
[FEATURE] - Корректировка количества разделов Text Fields

### ISSUE THREAD

**Issue by Evgeniy-93** [admiral-team/admiralui-ios#99]
![Simulator Screen Shot - iPhone 8 - 2022-05-23 at 16 30 03](https://user-images.githubusercontent.com/101252323/169830542-85492483-d254-4f75-b796-6f3b9af5198b.png)
**Описание задачи:**
в фигме 8 разделов, по факту в сборке 6. Не хватает Card Number, SMS code. Что было сделано - раздел Standard раскрыли и он теперь идет отдельно

**Фреймворк**
Text Fields

**Ресурсы:**

<img width="401" alt="Снимок экрана 2022-05-23 в 16 29 58" src="https://user-images.githubusercontent.com/101252323/169830443-7e359936-83d1-42f6-b86c-b6985b526fb7.png">
![Simulator Screen Shot - iPhone 8 - 2022-05-23 at 16 30 03](https://user-images.githubusercontent.com/101252323/169830462-da5218d8-17bc-450b-80e2-320f6ef4cd30.png)

**Comment by KirBorisov96** [comment]
4h
